version: '3.8'

services:
  client1:
    image: alpine
    container_name: client1
    command: ["ping", "-c", "4", "192.168.20.2"]
    networks:
      vlan:
        ipv4_address: 192.168.10.2

  client2:
    image: alpine
    container_name: client2
    command: ["ping", "-c", "4", "192.168.10.2"]
    networks:
      vlan:
        ipv4_address: 192.168.20.2

networks:
  vlan:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.10.0/24
