jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_RAM: 4g  # Increase Docker memory to 4 GB

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Install Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose
    
    - name: Set Docker Memory Limit
      run: |
        sudo sysctl -w vm.max_map_count=262144
        sudo sysctl -w fs.inotify.max_user_watches=524288
        sudo sysctl -w fs.file-max=2097152
    
    - name: Build Docker Compose
      run: |
        docker-compose up -d --build
    
    - name: Link Networks
      run: |
        docker network connect scalable-traffic-management-in-enterprise-networks-using-vlans-qos-and-redundancy-protocols_vlan10 client2
    
    - name: Test Connectivity
      run: |
        docker exec client1 ping -c 4 192.168.20.2
    
    - name: Clean up Docker
      run: |
        docker-compose down
